### ISSUE TITLE
Unable to cast object of type 'Microsoft.IIS.Administration.AccessManagement.Startup' to type 'Microsoft.IIS.Administration.Core.IModule'

### ISSUE THREAD

**Issue by 3400442579** [Microsoft/IIS.Administration#174] opened 2017-12-04 04:48 UTC
发生了 System.InvalidCastException
  HResult=0x80004002
  Message=Unable to cast object of type 'Microsoft.IIS.Administration.AccessManagement.Startup' to type 'Microsoft.IIS.Administration.Core.IModule'.
  Source=<无法计算异常源>
  StackTrace:
   at Microsoft.IIS.Administration.ModuleLoader.LoadModule(String assemblyName) in D:\dev\IIS.Administration-2.2.0\src\Microsoft.IIS.Administration\Extensibility\ModuleLoader.cs:line 46
   at Microsoft.IIS.Administration.Startup.LoadPlugins(ModuleLoader loader, String[] assemblyNames) in D:\dev\IIS.Administration-2.2.0\src\Microsoft.IIS.Administration\Startup.cs:line 237
   at Microsoft.IIS.Administration.Startup.ConfigureServices(IServiceCollection services) in D:\dev\IIS.Administration-2.2.0\src\Microsoft.IIS.Administration\Startup.cs:line 66

**Comment by jimmyca15** [comment] 2017-12-04 17:16
Can you provide some information for this stack trace? For instance, when did this happen and on what OS.

**Comment by 3400442579** [comment] 2017-12-05 03:57
window 2012 R2 
.net core 2.0
TargetFramework:netcoreapp2.0
RuntimeFrameworkVersion:2.0.0
debug

StackTrace	"   at Microsoft.IIS.Administration.ModuleLoader.LoadModule(String assemblyName) in D:\\dev\\IIS.Administration-2.2.0\\src\\Microsoft.IIS.Administration\\Extensibility\\ModuleLoader.cs:line 46\r\n   at Microsoft.IIS.Administration.Startup.LoadPlugins(ModuleLoader loader, String[] assemblyNames) in D:\\dev\\IIS.Administration-2.2.0\\src\\Microsoft.IIS.Administration\\Startup.cs:line 237\r\n   at Microsoft.IIS.Administration.Startup.ConfigureServices(IServiceCollection services) in D:\\dev\\IIS.Administration-2.2.0\\src\\Microsoft.IIS.Administration\\Startup.cs:line 66"

**Comment by 3400442579** [comment] 2017-12-05 04:02
我想把系统升级为 .net core 2.0 ,修改后就无法运行。

**Comment by jimmyca15** [comment] 2017-12-06 01:42
.NET Core 1.0.* is required to run the service. When the IIS Administration API 2.2.0 installs it makes sure that .NET Core 1.0.7 is installed on the machine. Was it running fine and then it broke when you installed .NET Core 2.0 or did you just try to run it on .NET 2.0

Also, are you just debugging the application or did you actually install it?

**Comment by 3400442579** [comment] 2017-12-06 02:51
debugging the application.
IIS Administration API 2.2.0.Net core 1.x upgrade.Net core 2.0。 

Microsoft.IIS.Administration.csproj：
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\build\sign.props" />
  <Import Project="..\..\build\version.props" />

  <PropertyGroup>
    <VersionPrefix>$(IISAdministrationVersion)</VersionPrefix>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <AssemblyName>Microsoft.IIS.Administration</AssemblyName>
    <OutputType>Exe</OutputType>
    <PackageId>Microsoft.IIS.Administration</PackageId>
    <RuntimeFrameworkVersion>2.0.0</RuntimeFrameworkVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="plugins\**" />
    <EmbeddedResource Remove="plugins\**" />
    <None Remove="plugins\**" />
  </ItemGroup>

  <ItemGroup>
    <None Update="wwwroot\**\*;Views\**\*">
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
    <None Update="Properties\PublishProfiles;node_modules;bower_components;**.xproj;**.user;**.vspscc;approot;log.txt;logs;config\**\*;plugins">
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
    <Content Update="bower.json;approot;log.txt;logs;config\**\*">
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Microsoft.IIS.Administration.Files.Core\Microsoft.IIS.Administration.Files.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MicroBuild.Core" Version="$(MicroBuildVersion)" />
    <PackageReference Include="Microsoft.AspNetCore.Antiforgery" Version="2.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication" Version="2.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting.Abstractions" Version="2.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Server.HttpSys" Version="2.0.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Routing" Version="2.0.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.CommandLine" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="2.0.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="2.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics" Version="2.0.1" />
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="4.4.0" />
  </ItemGroup>

  <ItemGroup Condition=" '$(SignType)' != '' ">
    <FilesToSign Include="$(IntermediateOutputPath)\$(TargetFileName);">
      <Authenticode>$(SigningIdentity)</Authenticode>
    </FilesToSign>
  </ItemGroup>

  
  <Target Name="AddGeneratedContentItems" BeforeTargets="AssignTargetPaths" DependsOnTargets="PrepareForPublish">
    <ItemGroup>
      <Content Include="wwwroot/**/*.js" CopyToPublishDirectory="PreserveNewest" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder);@(Content)" />
    </ItemGroup>
  </Target>
  <ProjectExtensions><VisualStudio><UserProperties config_4appsettings_1json__JSONSchema="" /></VisualStudio></ProjectExtensions>

  <Target Name="PostcompileScript" AfterTargets="Build">
    <Exec Command="bower install" />
  </Target>

  <Target Name="PrepublishScript" BeforeTargets="PrepareForPublish">
    <Exec Command="bower install" />
  </Target>

</Project>

**Comment by jimmyca15** [comment] 2018-04-09 16:35
This issue only occurs while debugging the application, and we have not been able to reproduce it. Closing this issue since no one else is reporting on it as well.

**Closed by jimmyca15** 2018-04-09 16:35 UTC
