### ISSUE TITLE
Not installed on Nano Server

### ISSUE THREAD

**Issue by swedays** [Microsoft/IIS.Administration#162] opened 2017-10-21 21:13 UTC
Hello. Not installed =( 

PS C:\IIS.Administration\setup> .\setup.ps1 Install -Verbose 
VERBOSE:Verifying user is an Administrator 
VERBOSE:Ok 
VERBOSE:Verifying user is an Administrator 
VERBOSE: Ok 
Checking installation requirements 
VERBOSE: Verifying IIS is enabled 
VERBOSE:Ok 
VERBOSE: Verifying Windows Authentication is Enabled 
VERBOSE:Ok 
VERBOSE: Verifying IIS-HostableWebCore is Enabled 
Rolling back 
Finished rolling back. 
C:\IIS.Administration\setup\setup.ps1 : A positional parameter cannot be found that accepts argument 'Error checking st 
ate of IIS-HostableWebCore'. 
At C:\IIS.Administration\setup\install.ps1:118 char:35 
+ ... $hostableWebCoreEnabled = .\dependencies.ps1 HostableWebCoreEnabled 
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
+ CategoryInfo : NotSpecified: (:) [Write-Error], ParameterBindingException 
+ FullyQualifiedErrorId : System.Management.Automation.ParameterBindingException,setup.ps1 

if you try to install the component, write this: 

PS C:\IIS.Administration\setup> Enable-WindowsOptionalFeature -Online -FeatureName IIS-HostableWebCore 
Feature name IIS-HostableWebCore is unknown. 
+ CategoryInfo : NotSpecified: (:) [Enable-WindowsOptionalFeature], COMException 
+ FullyQualifiedErrorId : Microsoft.Dism.Commands.EnableWindowsOptionalFeatureCommand

**Comment by jimmyca15** [comment] 2017-10-22 01:18
What version of the API are you trying to install and on what version of Nano Server?

**Comment by swedays** [comment] 2017-10-22 10:34
v1.0.36

**Comment by jimmyca15** [comment] 2017-10-23 15:59
Have you tried using a newer version of the API? v1.0.36 is old and we only support the latest release. There is currently a known issue when installing v2.1.0 on Nano Server https://github.com/Microsoft/IIS.Administration/issues/137 that requires a modification to a PS script to correct, but v2.0.0 should work as expected right after download.

We've checked in the fix for the PowerShell script issue in v2.1.0. It can be found here https://github.com/Microsoft/IIS.Administration/pull/141 to manually make the modifications. Ideally I'd like to upload the updated PS scripts to the 2.1.0 release but have I have not been able to do so.

**Comment by swedays** [comment] 2017-10-24 21:03
@jimmyca15 Thanks for the help! It started, but the browser produces the following error: the connection was dropped. ERR_CONNECTION_RESET. In all browsers such a problem.

**Comment by jimmyca15** [comment] 2017-10-25 16:28
What version did you install? Did you confirm that port 55539 is open so that you can connect to the API externally?

**Comment by swedays** [comment] 2017-10-25 16:58
v2.0.0
The port was opened by the following command:
New-NetFirewallRule -Name "IIS Administration" -DisplayName "IIS Administration" -Protocol TCP -LocalPort 55539 -Action Allow -Enabled True

**Comment by jimmyca15** [comment] 2017-10-26 00:38
The IIS Administration API automatically creates a certificate and installs it during installation. Are you running inside of a container? The connection reset error makes me think that it is due to a firewall or a port not being exposed.

**Comment by swedays** [comment] 2017-10-27 16:36
Nano server works like a normal virtual machine.
It turns out that during the installation process the service could not start (I'm not careful), because the installation failed. However, it's strange, it starts up in a manual process, but the service does not want to start.
If you try to start the service manually, you get the following error:
Error 1053: The service did not respond in a timely fashion

**Comment by jimmyca15** [comment] 2017-11-07 00:13
The output during installation showed that the service failed to install?

If the service installed correctly and _then_ restarting the service failed that is a different issue. If the service did install correctly which is what you mentioned happened before then try running the application directly.

```
dotnet "C:\Program Files\IIS Administration\2.0.0\Microsoft.IIS.Administration\Microsoft.IIS.Administration.dll"
```

If the service installed correctly and then fails to restart my guess is that the system does not have write access to the configuration file (appsettings.json) and api keys file (api-keys.json). This can happen if you change the ACLs to manually write to these files and accidentally take away the SYSTEM's write privileges.

Also we have a new [2.2.0 release](https://github.com/Microsoft/IIS.Administration/releases/tag/v2.2.0) available.

**Comment by jimmyca15** [comment] 2018-01-22 18:12
Closing due to inactivity. The latest version (2.2.0) does not reproduce this issue.

**Closed by jimmyca15** 2018-01-22 18:12 UTC
