### ISSUE TITLE
consume with soapui

### ISSUE THREAD

**Issue by cankaya07** [Microsoft/IIS.Administration#173] opened 2017-11-30 13:59 UTC
i all the time getting that unauthorized problem. 
this is my request from soapui

Request:
GET https://localhost:55539/api/webserver/monitoring HTTP/1.1
Accept-Encoding: gzip,deflate
Access-Token: Bearer jH8_G5LOWj3VRTDjKA6jNc_f-k2lwj3WrFsAA47Hplt1iGyTjaD9Iw
Authorization: Basic Yxxxxxxxxxxxxxx=
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36 OPR/47.0.2631.71
Accept: application/hal+json
Host: localhost:55539
Connection: Keep-Alive

Response:
HTTP/1.1 401 Unauthorized
Content-Length: 0
Server: Microsoft-HTTPAPI/2.0
WWW-Authenticate: Negotiate
WWW-Authenticate: NTLM
Date: Thu, 30 Nov 2017 13:53:35 GMT

**Comment by jimmyca15** [comment] 2017-11-30 17:18
The response is unauthorized due to lack of Windows Credentials. The default settings of the IIS Administration API require Windows Authentication on top of the access token.

**Comment by jimmyca15** [comment] 2017-12-04 22:46
By design, the API will respond with 401 unless Windows credentials were provided with the request or the API has been configured to not require Windows credentials. I will close the issue. If you have more questions please either reopen the issue or create a new one.

**Closed by jimmyca15** 2017-12-04 22:46 UTC
