### ISSUE TITLE
Unable to upgrade to 2.3.0 from 2.2.0 Server 2016

### ISSUE THREAD

**Issue by laurasoutar** [Microsoft/IIS.Administration#275] opened 2019-07-23 10:33 UTC
I have been trying to update from 2.2.0 to 2.3.0 on Server 2016.  The 2.3.0 installer keeps failing with a 0x80070643 error.  Log file attached.

I have attempted a full uninstall of 2.2.0 and a clean install of 2.3.0 to no avail, no matter what I try the installer keeps falling over with the same error.

I require 2.3.0 in order to make use of the app pool recycle feature rather than stop/start. 

[Microsoft_IIS_Administration_2.3.0_20190723112110.log](https://github.com/microsoft/IIS.Administration/files/3421580/Microsoft_IIS_Administration_2.3.0_20190723112110.log)

**Comment by bariscaglar** [comment] 2019-07-23 20:31
@shhsu please take a look.

**Comment by bariscaglar** [comment] 2019-07-23 20:33
Similar to #274

**Comment by shhsu** [comment] 2019-07-23 23:00
Sorry for the delay, unfortunately this file doesn't have enough information.
Can I have the different log file from the temp directory `Microsoft_IIS_Administration_2.3.0_*_iis_administration_msi.log`. It should have more information that is relevant

**Comment by shhsu** [comment] 2019-07-23 23:38
Also please search in Event Viewer and see if you can find any application level log for `Microsoft IIS Administration API` especially around the time of installation.

**Comment by laurasoutar** [comment] 2019-07-24 06:46
HI, Have attached the file in question, can't see anything in useful in the event logs regarding the installation.

Let me know if you need anything else.

[Microsoft_IIS_Administration_2.3.0_20190723112110_000_iis_administration_msi.log](https://github.com/microsoft/IIS.Administration/files/3425339/Microsoft_IIS_Administration_2.3.0_20190723112110_000_iis_administration_msi.log)

**Comment by laurasoutar** [comment] 2019-07-24 08:50
I had a quick look at the msi error log and figured out it was because the group check in the security.ps1 script has a flag set to false to skip if the group already exists, I am assuming this flag should be set to true on an upgrade scenario.  
I found a workaround by fully uninstalling 2.2.0, delete the group (and a few other things that don't seem to be cleaned up by the uninstall), logged off, logged on again then re-ran the 2.3.0 installer successfully this time.
I'm happy to run with my workaround, but it does seem to be a bug in the installer scripts.

**Comment by shhsu** [comment] 2019-07-24 16:58
@laurasoutar 
Thanks for looking and finding the workaround. The purpose of `$skipIfExists` flag only determine whether the function should throw if the existing group exists. It should be the same for both install and upgrade scenario. (Which is false because we just want to proceed with the installation with the group object retrieved)

However, `CreateLocalGroup` does seem to be the cause of your issue. Something is causing it to return `null` when it is not expected to.

Can you confirm if the powershell command `Get-LocalGroup` and `New-LocalGroup` are present on your system?

**Comment by laurasoutar** [comment] 2019-07-25 10:46
HI @shhsu 

The commands in question are present on my installation of powershell.

**Comment by shhsu** [comment] 2019-07-25 16:42
Thanks @laurasoutar again for the information. I will follow up on the root cause of this issue.

**Comment by shhsu** [comment] 2019-08-12 21:33
Closing

**Closed as completed by shhsu** 2019-08-12 21:33 UTC
