### ISSUE TITLE
Can't run the website

### ISSUE THREAD

**Issue by MaherJendoubi** [Microsoft/IIS.Administration#8] opened 2016-09-23 16:09 UTC
![image](https://cloud.githubusercontent.com/assets/1798510/18792975/04672d3a-81b9-11e6-9c1c-692d9aa0476a.png)

**Comment by jimmyca15** [comment] 2016-09-23 16:13
This appears to be a continuation of #1. Did you run the Configure-DevEnvironment.ps1 script mentioned in the readme?

**Comment by MaherJendoubi** [comment] 2016-09-23 16:35
@jimmyca15 no but I get this message 
![image](https://cloud.githubusercontent.com/assets/1798510/18793746/828d0c68-81bc-11e6-8a92-f461c1114757.png)

**Comment by jimmyca15** [comment] 2016-09-23 17:05
Oh thanks for finding that. The issue is that it is trying to invoke a script that had its name changed from constants.ps1 to globals.ps1. I will make the fix.

**Comment by jimmyca15** [comment] 2016-09-23 17:15
The issue with the development setup script was fixed in the latest commit. You should be able to run it and then run the api from visual studio.

**Comment by MaherJendoubi** [comment] 2016-09-23 17:21
![image](https://cloud.githubusercontent.com/assets/1798510/18795059/f5325376-81c2-11e6-9fa5-8f57487c6ff3.png)

**Comment by jimmyca15** [comment] 2016-09-23 17:23
Looks good. You should be a member of the **IIS Administrators** group now and the error you were getting from launching VS should be gone.

**Comment by MaherJendoubi** [comment] 2016-09-23 17:26
Jimmy I still have the same error

**Comment by MaherJendoubi** [comment] 2016-09-23 17:27
![image](https://cloud.githubusercontent.com/assets/1798510/18795207/b278bbb4-81c3-11e6-842b-f69d6241dd90.png)

**Comment by jimmyca15** [comment] 2016-09-23 17:39
Can you confirm that you are in the **IIS Administrators** group and try running without debugging? If that is true then this could be an issue in the Visual Studio tooling that is launching the process.

**Comment by MaherJendoubi** [comment] 2016-09-23 17:46
I am in the IIS Administrators group.

**Comment by MaherJendoubi** [comment] 2016-09-23 17:50
![image](https://cloud.githubusercontent.com/assets/1798510/18795884/f3e2c7ea-81c6-11e6-8169-2bacd7705c0b.png)

**Comment by jimmyca15** [comment] 2016-09-23 18:03
The script should have fixed that. 
In "&lt;SolutionRoot&gt;\\.vs\config\applicationHost.config" change

           <section name="anonymousAuthentication" overrideModeDefault="Deny" />
           <section name="windowsAuthentication" overrideModeDefault="Deny" />

to 

          <section name="anonymousAuthentication" overrideModeDefault="Allow" />
          <section name="windowsAuthentication" overrideModeDefault="Allow" />

This should be done automatically in a future version of the VS tooling.

**Comment by jimmyca15** [comment] 2016-09-23 18:04
I will try to reproduce your issue. The error should be gone if you remove the windows authentication requirements from the web.config for the Microsoft.IIS.Administration project.

**Comment by MaherJendoubi** [comment] 2016-09-23 20:00
Let me give you more context:
1) I forked your project and I updated to 1.0.1 as mentioned in my PR https://github.com/Microsoft/IIS.Administration/pull/10

2) even "<SolutionRoot>\.vs\config\applicationHost.config" change doesn't fix the problem.

3) I suspect that the main problem is due to the tooling 1.0.1 https://github.com/aspnet/Tooling/issues/779

**Comment by jimmyca15** [comment] 2016-09-23 20:22
I see. If you want to run the application you can remove the Windows Authentication requirements from the web.config then the tooling should no longer have an error connecting to the dotnet process. I will still investigate this to make sure there isn't another problem.

**Comment by MaherJendoubi** [comment] 2016-09-23 20:44
![image](https://cloud.githubusercontent.com/assets/1798510/18800806/4e7e3bae-81df-11e6-9adf-d6d2b99a7b93.png)

**Comment by jimmyca15** [comment] 2016-09-24 21:18
I just cloned the project and ran it on a separate machine. I was originally getting the same error you were

![image](https://cloud.githubusercontent.com/assets/21000428/18811334/3ce90f9a-8261-11e6-8a88-1a9eadce92ce.png)

 then I ran the Configure-DevEnvironment.ps1 script. After that I got this error, probably because the group settings the script just altered had not percolated through to VS.

![image](https://cloud.githubusercontent.com/assets/21000428/18811349/9616eb3c-8261-11e6-8e4a-554553a38d08.png)

 I restarted visual studio. After that the error went away and I was able to debug.

**Comment by MaherJendoubi** [comment] 2016-09-24 21:48
I did the same steps you did but I still having this error : 
![image](https://cloud.githubusercontent.com/assets/1798510/18811490/63acef34-82b1-11e6-9cbf-7ead5f31287d.png)

**Comment by MaherJendoubi** [comment] 2016-09-24 21:54
Jimmy there is something weird on my Visual Studio, I can't start debugging any asp.net core app :(

**Comment by MaherJendoubi** [comment] 2016-09-25 23:29
@jimmyca15 I have this issue now https://github.com/Microsoft/IIS.Administration/issues/11

**Comment by jimmyca15** [comment] 2016-09-26 03:16
Debugging for the application is working now so I'm going to close this issue.

**Closed by jimmyca15** 2016-09-26 03:16 UTC
