### ISSUE TITLE
Centralized Certificate Store "Bad Data" error

### ISSUE THREAD

**Issue by CoskunSunali** [Microsoft/IIS.Administration#182] opened 2018-03-10 05:49 UTC
Hi,

It seems that the management UI has issues displaying some certificates with the identity impersonation involved.

Even though the certificates work fine when a site is accessed, the management UI displays a "red cross" with the "Bad Data" error being displayed.

The identity being set for the feature has all required access rights to reach the shared directory - otherwise https bindings would not work I guess.

One important thing to note is that if the feature identity is changed to, let's say an Administrator, the UI all of a sudden starts displaying the certificates without any issues.

Further analysis can be read at https://github.com/ridercz/AutoACME/issues/14

Would you mind sharing your thoughts?

Thanks!

![image](https://user-images.githubusercontent.com/6509380/37238827-e909b712-243f-11e8-8046-916f2c523d29.png)

**Comment by CoskunSunali** [comment] 2018-03-10 05:57
@bariscaglar Any assistance you might be of would be highly appreciated. I might also directly email you with a "test certificate" that might help you reproduce the issue on a team member's computer.

Bests,
Coskun

**Comment by bariscaglar** [comment] 2018-03-13 21:54
Hi Coskun, thank you for contacting us. Unfortunately this is the wrong location for this issue as IIS Manager UI (inetmgr.exe) is part of Windows and is not on GitHub. @jimmyca15 could you file a vNext bug, close this issue and take a look at the bug when you get a chance? @CoskunSunali please @mention Jimmy in the AutoAcme#14 issue and he can circle back there once he has something to share. Thanks!

**Comment by jimmyca15** [comment] 2018-03-13 21:59
@CoskunSunali 

Do you have a way to definitively reproduce this issue? You mentioned you think it has something to do with the impersonation involved in reading the certificates. Is there something special about the account that you are impersonating with?

**Comment by CoskunSunali** [comment] 2018-03-14 05:53
@bariscaglar Hi and thanks for getting back! I'll go ahead and reply to @jimmyca15's question at ridercz/AutoACME#14 directly.

@jimmyca15 Hi and thanks for your interest in taking a look at the issue. I will quote your comment and reply to it on ridercz/AutoACME#14 since it is not related to this repo as it seems.

**Comment by CoskunSunali** [comment] 2018-03-14 06:24
@jimmyca15 @bariscaglar I tried to write a comment listing step by step instructions to reproduce the issue at https://github.com/ridercz/AutoACME/issues/14#issuecomment-372917301

Thanks for your interest!

**Comment by jimmyca15** [comment] 2018-03-14 16:38
Thanks for doing that @CoskunSunali. I am looking over the reproduction steps now. Since this is unrelated to the IIS Administration API I will close this issue.

**Closed by jimmyca15** 2018-03-14 16:38 UTC

**Comment by CoskunSunali** [comment] 2018-03-16 11:34
Hi @jimmyca15 and @bariscaglar,

Baris, thank you for your understanding regarding me opening the issue in the wrong repo (unintentionally) and another thank you for connecting me with Jimmy so that he can have a look.

Jimmy, thank you for your efforts to get the issue fixed!
